name: marburg-tree
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - biopython
  - nextclade
  - pip
  - PyYAML
  - python-dateutil
  - snakemake
  - ncbi-datasets-cli >=16.29.0
  - augur
  - click